application: webm-dashboard
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /drilldown/.*
  script: drilldown.py

- url: /gerrit/.*
  script: gerrit.py

- url : /analysis/.*
  script: analysis.py

- url : /commit_viewer/.*
  script: commit_view.py

- url: /_ah/warmup
  login: admin
  script: main.py

- url: .*
  script: main.py

includes:
- mapreduce/include.yaml
