application: webm-dashboard
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /drilldown/.*
  script: drilldown.py

- url: /gerrit/.*
  script: gerrit.py

- url : /analysis/.*
  script: analysis.py

- url : /commit_viewer/.*
  script: commit_view.py

- url: /home
  mime_type: text/html
  static_files: home.html
  upload: /home.html

- url: .*
  script: main.py

includes:
- mapreduce/include.yaml
