application: webm-dashboard
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /drilldown/.*
  script: drilldown.py

- url: .*
  script: main.py

includes:
- mapreduce/include.yaml
